### ISSUE TITLE
No support for cancellation date?

### ISSUE THREAD

**Issue by donholly** [nov/itunes-receipt#11]
Per: https://developer.apple.com/library/ios/releasenotes/General/ValidateAppStoreReceipt/Chapters/ReceiptFields.html

There is a cancellation date provided with the receipt to notify of subscriptions that are no longer valid.

**Comment by nov** [comment]
Sorry, I'm not going to add new features to this gem any more..

**Comment by donholly** [comment]
No worries,
@jonmumm nailed it over here:
https://github.com/jonmumm/itunes-receipt/commit/88a312879eb318c61806cce6f7578447613554e5
