### ISSUE TITLE
Where to set Shared secrent for Auto renewal subscriptions?

### ISSUE THREAD

**Issue by dhanu** [nov/itunes-receipt#5]
This gem is working perfectly for non renewal subscriptions.

For auto renewal subscriptions verification fails.  Auto renewal subscription needs shared secret but i don't know where to set My Shared Secret in the code.

Can you please help me....

**Comment by nov** [comment]
You can set `Itunes.shared_secret = "foobar"`
ref) https://github.com/nov/itunes-receipt/blob/master/lib/itunes.rb#L34

However, to be honest, since I implemented this gem long time ago and I haven't used Auto renewal subscriptions, it's not tested...

**Comment by dhanu** [comment]
Thanks.. It works fine after setting shared secret like this. 

Itunes.shared_secret = "foobar"
