### ISSUE TITLE
JSON Conversion Missing Data

### ISSUE THREAD

**Issue by kaomte** [nov/itunes-receipt#9]
When converting to JSON, many of the fields are missing, most notably the in app purchases are missing. 

The json conversion method was added in b99192520526c8d93a74086234bddb4b39678f43. 

Was there a specific reason for adding the as_json method? Removing the as_json method seems to resolve the issue.

**Comment by nov** [comment]
hum, seems unnecessary.
@r4m, do you remember why you added `to_h` and `to_json` in the commit?

**Comment by nov** [comment]
I've just removed the method.
If @r4m is ok, or no response for a while, I'll release new version with this removal.

Thanks for your report.

**Comment by nov** [comment]
BTW, in what case, do you convert `Itunes::Receipt` instance into JSON, @kaomte ?

**Comment by kaomte** [comment]
I'm storing the receipt in a database field.

**Comment by nov** [comment]
Ah, then I recommend you to store what you received from apple server directly.
It's always the best way handling singed/encrypted security tokens.

**Comment by kaomte** [comment]
@nov Yes, that's the ideal solution that I'm working towards, but I have not yet figured out a way to access that data from Itunes::Receipt. Any suggestions?

**Comment by nov** [comment]
Aren't you giving raw receipt data to this gem?

**Comment by kaomte** [comment]
You mean the base64 encoded data? You know I never thought to try to decode that, it just seemed easier to get the decoded version from the server response.

**Comment by nov** [comment]
This gem doesn't `decode` data.
It send the given `encoded` data to Apple server, and get a JSON response.
The `encoded` data is verifiable (=include signature), but the response isn't.

**Comment by kaomte** [comment]
But the Apple server _does_ verify the encoded data and assuming we trust the connection to the Apple server, we can then simply rely on the response, correct?

**Comment by nov** [comment]
At the time you accessing to Apple server, yes.
In future, no.

**Comment by kaomte** [comment]
Ah, I see what you're saying. Thanks for the explanation!

**Comment by r4m** [comment]
@nov I probably added them because I intentionally wanted to distinguish the struct of the json compared to the hash one. I do not remember exactly at the moment the reason why. I'll do some test in the next week with version 1.0.0 and then I'll try again when you release an update with the aforementioned commit
